name: Test on cvmfs

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  BUILD_TYPE: Release

jobs:
  ubuntu-minimal:
    runs-on: ubuntu-22.04
    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@v2

    - name: Load CernVM-FS
      run: |
        source /cvmfs/sft.cern.ch/lcg/views/LCG_102/x86_64-ubuntu2204-gcc11-opt/setup.sh
        root --version
        echo "env"
        env

    - uses: actions/checkout@v3

    - name: Configure CMake
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        pwd
        ls -lahtr /home/runner/work/mc
        ls -lahtr /home/runner/work/mc/mc
        echo ${{github.workspace}}
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Install
      run: cmake --install ${{github.workspace}}/build --prefix ${{github.workspace}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        root --version
        ctest -C ${{env.BUILD_TYPE}} --verbose
      
