name: Test on cvmfs

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  ubuntu-minimal:
    runs-on: ubuntu-22.04
    steps:
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - name: Load CernVM-FS
      run: |
        source /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.26.04/x86_64-ubuntu22-gcc112-opt/bin/thisroot.sh
        root --version
