name: Test on macos

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  BUILD_TYPE: Release

jobs:
  macOS-minimal:
    runs-on: macos-12
    steps:

	- name: Install ROOT and Geant4
	  run: |
	  	wget https://github.com/mzks/macos_root_geant4_binaries/releases/download/0.1/geant4.11.0.2.tar.gz
	  	wget https://github.com/mzks/macos_root_geant4_binaries/releases/download/0.1/root6.26.04.tar.gz
		mkdir -p ~/.local/geant4
		mkdir -p ~/.local/root
		tar xf geant4.11.0.2.tar.gz -C ~/.local/geant4/11.0.2
		tar xf root6.26.04.tar.gz -C ~/.local/root/6.26.04

        #    - name: Install dependencies
        #      run: sudo apt -y install dpkg-dev cmake g++ gcc binutils libx11-dev libxft-dev libxext-dev libssl-dev gfortran libpcre3-dev xlibmesa-glu-dev libglew-dev libftgl-dev libmysqlclient-dev libfftw3-dev libcfitsio-dev graphviz-dev libavahi-compat-libdnssd-dev libldap2-dev libxml2-dev libkrb5-dev libgsl0-dev qtwebengine5-dev cmake-curses-gui libxpm4 libxerces-c-dev libxpm-dev libxmu-dev libfreetype6-dev qtbase5-dev qttools5-dev-tools libgtest-dev libeigen3-dev qtbase5-dev qtchooser qt5-qmake qtbase5-dev-tools libmotif-common libmotif-dev

    - uses: actions/checkout@v3

    - name: Configure CMake
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Install
      run: cmake --install ${{github.workspace}}/build --prefix ${{github.workspace}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        root --version
        ctest -C ${{env.BUILD_TYPE}} --verbose
      
