name: Test on macos

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  BUILD_TYPE: Release

jobs:
  macos_build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install qt@5 gsl xerces-c
          export PATH="/usr/local/opt/qt@5/bin:$PATH"
          source /Users/runner/.bash_profile
          export PATH=$(brew --prefix qt5)/bin:$PATH
          export LDFLAGS="-L/usr/local/opt/qt@5/lib"
          export CPPFLAGS="-I/usr/local/opt/qt@5/include"
          export PKG_CONFIG_PATH="/usr/local/opt/qt@5/lib/pkgconfig"

      - name: Install ROOT and Geant4
        run: |
          wget https://github.com/mzks/macos_root_geant4_binaries/releases/download/0.2/macos12-clang1316-root-6.26.4.tar.gz --quiet
          wget https://github.com/mzks/macos_root_geant4_binaries/releases/download/0.2/macos12-clang1316-geant4-11.0.2.tar.gz --quiet
          mkdir -p ~/.local
          tar xf macos12-clang1316-root-6.26.4.tar.gz -C ~/.local
          tar xf macos12-clang1316-geant4-11.0.2.tar.gz -C ~/.local

          source ~/.local/root/6.26.4/bin/thisroot.sh
          source ~/.local/geant4/11.0.2/bin/geant4.sh

      - name: cmake
        run: |
          source ~/.local/root/6.26.4/bin/thisroot.sh
          source ~/.local/geant4/11.0.2/bin/geant4.sh
          root --version
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DXERCESC_ROOT_DIR=/usr/local/Cellar/xerces-c/3.2.3 -DXercesC_INCLUDE_DIR=/usr/local/Cellar/xerces-c/3.2.3/include


      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Install
        run: cmake --install ${{github.workspace}}/build --prefix ${{github.workspace}}

      - name: Test
        working-directory: ${{github.workspace}}/build
          # Execute tests defined by the CMake configuration.  
          # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: |
          source ~/.local/root/6.26.4/bin/thisroot.sh
          source ~/.local/geant4/11.0.2/bin/geant4.sh
          root --version
          ctest -C ${{env.BUILD_TYPE}} --verbose
