name: Test on macos

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  BUILD_TYPE: Release

jobs:
  macos_build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install qt@5 gsl xerces-c
          echo 'export PATH="/usr/local/opt/qt@5/bin:$PATH"' >> /Users/runner/.bash_profile
          source /Users/runner/.bash_profile
          export PATH=$(brew --prefix qt5)/bin:$PATH
          export LDFLAGS="-L/usr/local/opt/qt@5/lib"
          export CPPFLAGS="-I/usr/local/opt/qt@5/include"
          export PKG_CONFIG_PATH="/usr/local/opt/qt@5/lib/pkgconfig"

      - name: Install ROOT and Geant4
        run: |
          wget https://github.com/mzks/macos_root_geant4_binaries/releases/download/0.1/geant4.11.0.2.tar.gz --quiet
          wget https://github.com/mzks/macos_root_geant4_binaries/releases/download/0.1/root6.26.04.tar.gz --quiet
          mkdir -p ~/.local/geant4
          mkdir -p ~/.local/root
          tar xf geant4.11.0.2.tar.gz -C ~/.local/geant4
          tar xf root6.26.04.tar.gz -C ~/.local/root

          source ~/.local/root/6.26.04/bin/thisroot.sh
          export PATH="${PATH}:${HOME}/.local/geant4/11.0.2/bin:${HOME}/.local/root/6.26.04/bin"
          export ROOTSYS="${HOME}/.local/root/6.26.04"
          export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${HOME}/.local/root/6.26.04/lib"
          export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}:${HOME}/.local/root/6.26.04/lib"
          export SHLIB_PATH="${SHLIB_PATH}:${HOME}/.local/root/6.26.04/lib"
          export LIBPATH="${LIBPATH}:${HOME}/.local/root/6.26.04/lib"
          export CMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}:${HOME}/.local/root/6.26.04:`brew --prefix xerces-c`/bin"
          export G4PARTICLEHPDATA="~/.local/geant4/11.0.1/share/Geant4-11.0.1/data/G4TENDL1.4"
          export G4NEUTRONHPDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4NDL4.6"
          export G4LEDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4EMLOW8.0"
          export G4LEVELGAMMADATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/PhotonEvaporation5.7"
          export G4RADIOACTIVEDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/RadioactiveDecay5.6"
          export G4PARTICLEXSDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4PARTICLEXS4.0"
          export G4PIIDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4PII1.3"
          export G4REALSURFACEDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/RealSurface2.2"
          export G4SAIDXSDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4SAIDDATA2.0"
          export G4ABLADATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4ABLA3.1"
          export G4INCLDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4INCL1.0"
          export G4ENSDFSTATEDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4ENSDFSTATE2.3"

      - name: cmake
        run: |
          source ~/.local/root/6.26.04/bin/thisroot.sh
          export PATH="${PATH}:${HOME}/.local/geant4/11.0.2/bin:${HOME}/.local/root/6.26.04/bin"
          export ROOTSYS="${HOME}/.local/root/6.26.04"
          export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${HOME}/.local/root/6.26.04/lib"
          export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}:${HOME}/.local/root/6.26.04/lib"
          export SHLIB_PATH="${SHLIB_PATH}:${HOME}/.local/root/6.26.04/lib"
          export LIBPATH="${LIBPATH}:${HOME}/.local/root/6.26.04/lib"
          export CMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}:${HOME}/.local/root/6.26.04:`brew --prefix xerces-c`/bin"
          export G4PARTICLEHPDATA="~/.local/geant4/11.0.1/share/Geant4-11.0.1/data/G4TENDL1.4"
          export G4NEUTRONHPDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4NDL4.6"
          export G4LEDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4EMLOW8.0"
          export G4LEVELGAMMADATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/PhotonEvaporation5.7"
          export G4RADIOACTIVEDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/RadioactiveDecay5.6"
          export G4PARTICLEXSDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4PARTICLEXS4.0"
          export G4PIIDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4PII1.3"
          export G4REALSURFACEDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/RealSurface2.2"
          export G4SAIDXSDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4SAIDDATA2.0"
          export G4ABLADATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4ABLA3.1"
          export G4INCLDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4INCL1.0"
          export G4ENSDFSTATEDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4ENSDFSTATE2.3"
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DXERCESC_ROOT_DIR=/usr/local/Cellar/xerces-c/3.2.3 -DXercesC_INCLUDE_DIR=/usr/local/Cellar/xerces-c/3.2.3/include


      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Install
        run: cmake --install ${{github.workspace}}/build --prefix ${{github.workspace}}

      - name: Test
        working-directory: ${{github.workspace}}/build
          # Execute tests defined by the CMake configuration.  
          # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: |
          source ~/.local/root/6.26.04/bin/thisroot.sh
          export PATH="${PATH}:${HOME}/.local/geant4/11.0.2/bin:${HOME}/.local/root/6.26.04/bin"
          export ROOTSYS="${HOME}/.local/root/6.26.04"
          export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${HOME}/.local/root/6.26.04/lib"
          export DYLD_LIBRARY_PATH="${DYLD_LIBRARY_PATH}:${HOME}/.local/root/6.26.04/lib"
          export SHLIB_PATH="${SHLIB_PATH}:${HOME}/.local/root/6.26.04/lib"
          export LIBPATH="${LIBPATH}:${HOME}/.local/root/6.26.04/lib"
          export CMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}:${HOME}/.local/root/6.26.04:`brew --prefix xerces-c`/bin"
          export G4PARTICLEHPDATA="~/.local/geant4/11.0.1/share/Geant4-11.0.1/data/G4TENDL1.4"
          export G4NEUTRONHPDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4NDL4.6"
          export G4LEDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4EMLOW8.0"
          export G4LEVELGAMMADATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/PhotonEvaporation5.7"
          export G4RADIOACTIVEDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/RadioactiveDecay5.6"
          export G4PARTICLEXSDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4PARTICLEXS4.0"
          export G4PIIDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4PII1.3"
          export G4REALSURFACEDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/RealSurface2.2"
          export G4SAIDXSDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4SAIDDATA2.0"
          export G4ABLADATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4ABLA3.1"
          export G4INCLDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4INCL1.0"
          export G4ENSDFSTATEDATA="~/.local/geant4/11.0.2/share/Geant4-11.0.2/data/G4ENSDFSTATE2.3"
          root --version
          ctest -C ${{env.BUILD_TYPE}} --verbose
